version: '3'
services:
  openresty:
    image: 'openresty'
    depends_on:
    - 'app'
    # - 'keycloak'
    ports:
    - '8000:8000'
    volumes:
    - './www/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
    # - './keycloak/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/keycloak.conf:ro'
  app:
    image: 'node:14-alpine'
    restart: 'always'
    depends_on:
    - 'api'
    user: 'node'
    volumes:
    - './www/var/www/app/app:/var/www/app'
    working_dir: '/var/www/app'
    expose:
    - '3000'
    entrypoint: ['yarn']
    command: ['start']
    stdin_open: true
  api:
    image: 'api'
    build: './www/var/www/api'
    restart: 'always'
    expose:
    - '8000'
    entrypoint: ['python3']
    command: ['./manage.py', 'runserver_plus', '0.0.0.0:8000']
    stdin_open: true
    environment:
    - 'PYTHONUNBUFFERED=1'
    volumes:
    - './www/var/www/api/www:/var/www'
#  keycloak:
#    image: 'jboss/keycloak:16.1.1'
#    container_name: 'keycloak'
#    restart: 'always'
#    environment:
#    - 'KEYCLOAK_USER=admin'
#    - 'KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}'
#    - 'DB_VENDOR=postgres'
#    - 'DB_ADDR=keycloak-postgresql'
#    - 'DB_PORT=5432'
#    - 'DB_DATABASE=keycloak'
#    - 'DB_USER=admin'
#    - 'DB_PASSWORD=${POSTGRES_PASSWORD}'
#    - 'PROXY_ADDRESS_FORWARDING=true'
#    depends_on:
#    - 'keycloak-postgresql'
#    ports:
#    - '9990:9990' # dev
#    - '8080:8080' # dev
#    expose:
#    - '8080'
#    - '9990'
#    command:
#    - '-b=0.0.0.0'
#    volumes:
#    - './keycloak/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml'
#  keycloak-postgresql:
#    image: 'postgres:14.5-alpine'
#    restart: 'always'
#    environment:
#    - 'POSTGRES_DB=keycloak'
#    - 'POSTGRES_USER=admin'
#    - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
#    expose:
#    - '5432'
#    volumes:
#    - 'postgresql:/var/lib/postgresql/data'
#volumes:
#  postgresql:
