# Generated by Django 3.1.7 on 2021-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
