"""
Django settings for www project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rb1f(&%h))m84m##63-4l$e7*yqlk&i2pqpxh!nt88xgx&*t3i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    'localhost',
    'api',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'graphene_django',
    'app'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'app.middleware.SessionRefresh',
]

ROOT_URLCONF = 'www.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'www.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

GRAPHENE = {
    'SCHEMA': 'app.graphql.schema'
}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:80',
    'http://localhost',
]

# # Django REST Framework configuration
# # https://www.django-rest-framework.org/#installation
# 
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'mozilla_django_oidc.contrib.drf.OIDCAuthentication',
#     ),
# }
# 
# 
# # Mozilla Django OIDC configuration
# # https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html
# 
# AUTHENTICATION_BACKENDS = (
#     'app.auth.OIDCAuthenticationBackend',
# )
# 
# OIDC_RP_SIGN_ALGO = "RS256"
# OIDC_RP_CLIENT_ID = os.environ['OIDC_RP_CLIENT_ID']
# OIDC_RP_CLIENT_SECRET = os.environ['OIDC_RP_CLIENT_SECRET']
# OIDC_OP_AUTHORIZATION_ENDPOINT = "http://keycloak/auth/realms/yields/protocol/openid-connect/auth"
# OIDC_OP_TOKEN_ENDPOINT = "http://keycloak/auth/realms/yields/protocol/openid-connect/token"
# OIDC_OP_USER_ENDPOINT = "http://keycloak/auth/realms/yields/protocol/openid-connect/userinfo"
# OIDC_OP_JWKS_ENDPOINT = "http://keycloak/auth/realms/yields/protocol/openid-connect/certs"
# OIDC_OP_LOGOUT_ENDPOINT = "http://keycloak/auth/realms/yields/protocol/openid-connect/logout"
# OIDC_STORE_ACCESS_TOKEN=True
# 
# OIDC_USERNAME_ALGO='app.utils.generate_username'
# 
# OIDC_CALLBACK_CLASS = 'app.views.OIDCAuthenticationCallbackView'
# 
# LOGIN_URL = 'oidc_authentication_init'
# LOGIN_REDIRECT_URL= "/"
# LOGOUT_REDIRECT_URL="/"
